### ISSUE TITLE
Error: package 'moveit_planners_ompl' depends on non-existent package 'ompl' and rosdep claims that it is not a system dependency.

### ISSUE THREAD

**Issue by lkj1114889770** [jontromanab/move_group_test#1]
Hi. I create a ros package to use move_group interface with c++,and in the package.xml, i add run depend moveit_planners_ompl,that is where error occurs.It tell me the follwing infoprmation:
[rosbuild] Building package move_group_test
Failed to invoke /opt/ros/kinetic/bin/rospack deps-manifests move_group_test
[rospack] Error: package 'moveit_planners_ompl' depends on non-existent package 'ompl' and rosdep claims that it is not a system dependency. Check the ROS_PACKAGE_PATH or try calling 'rosdep update'

CMake Error at /opt/ros/kinetic/share/ros/core/rosbuild/public.cmake:129 (message):

Failed to invoke rospack to get compile flags for package
'move_group_test'.  Look above for errors from rospack itself.  Aborting.
Please fix the broken dependency!
And when i use rosfind pack ompl, it also tell me no package called ompl. so is that means there is no package called ompl, but how can i solve the problem of the dependency of moveit_planners_ompl?

ROS Distro: [Kinetic]
OS Version: Ubuntu 16.04

**Comment by jontromanab** [comment]
@lkj1114889770 glad that you solved the problem. Sorry for the late reply. Was out for some long due work.

Thank you very much @gavanderhoorn for looking after this.
Please let me know if you have any other problem.
